version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  helios-server:
    build:
      context: ./helios_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - TASK_STORAGE_PATH=/var/helios/tasks
    volumes:
      - /var/helios/tasks:/var/helios/tasks
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  helios-worker:
    build:
      context: ./helios_server
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TASK_STORAGE_PATH=/var/helios/tasks
    volumes:
      - /var/helios/tasks:/var/helios/tasks
      - /var/run/docker.sock:/var/run/docker.sock
    command: python worker.py
    restart: unless-stopped
    deploy:
      replicas: 2

volumes:
  redis_data: